#define LANG_SOURCE_FILE_EXTENSION   ".wtf"
#define LANG_TREE_PRE_FILE_EXTENSION ".wst"
#define LANG_TREE_BCK_FILE_EXTENSION ".wxt"

#define LANG_SOURCE_DEFAULT_FILE     "program" LANG_SOURCE_FILE_EXTENSION
#define LANG_TREE_PRE_DEFAULT_FILE   "program" LANG_TREE_PRE_FILE_EXTENSION
#define LANG_TREE_BCK_DEFAULT_FILE   "program" LANG_TREE_BCK_FILE_EXTENSION
